import Head from "next/head"
import Link from "next/link"
import { useSelector, useDispatch } from 'react-redux';
import styles from "../styles/Home.module.css"
import { state } from "../interfaces/store"
import { useEffect, useState } from "react"
import { setData } from "../redux/slices/dataSlice";
import { fetchThunk } from "../redux/store";


export default function Home() {
  const [lastWeekId, setLastWeekId] = useState(0)

  const lastWeek: number = useSelector(
    (state: state) => state.data.weeks[state.data.weeks.length - 1].id
  )

  const dispatch: any = useDispatch()

  useEffect(() => {
    // dispatch(fetchThunk)
    setLastWeekId(lastWeek)
  }, [lastWeek])

  return (
    <div className={styles.container}>
      <Head>
        <title>Budget</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={()=>{
        dispatch(fetchThunk)
      }} >Fetch</button>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Budget!</a>
        </h1>
        <nav>
          <ul>
            <li>
              <Link href={`/dashboard/${lastWeekId}`}>Dashboard</Link>
            </li>
            <li>
              <Link href={`/add-store`}>Nueva Tienda</Link>
            </li>
          </ul>
        </nav>
      </main>
    </div>
  )
}
